### ISSUE TITLE
Data prepare.

### ISSUE THREAD

**Issue by hieutrinhds** [yanbeic/VAL#1]
I got this errors when I try to run python generate_caption_pairs.py --dataset='fashion_iq'

Traceback (most recent call last):
  File "generate_tags.py", line 10, in <module>
    'dataset', "fashion_iq or shoes")
  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow_core\python\platform\flags.py", line 58, in wrapper
    return original_function(*args, **kwargs)
TypeError: DEFINE_string() missing 1 required positional argument: 'help'

**Comment by yanbeic** [comment]
Which python and tensorflow are used? It is likely caused similarly to [issue](https://github.com/tensorflow/benchmarks/issues/218)
