### ISSUE TITLE
No such file or directory: 'save_model/fashion_iq/val_resnet_v2_50_ml/query_images.npy'

### ISSUE THREAD

**Issue by huynhtruc0309** [yanbeic/VAL#6]
I have some problems. Please help me.
1) I am running `bash scripts/run_fashion_iq.sh` and falling to this error.
```
Traceback (most recent call last):
  File "test_val.py", line 220, in <module>
    main()
  File "test_val.py", line 48, in main
    query_images = np.load(filename)
  File "/home/huynhtruc0309/anaconda3/envs/truchlp/lib/python3.7/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'save_model/fashion_iq/val_resnet_v2_50_ml/query_images.npy'
```

2) And can you provide your checkpoint in the paper

**Comment by huynhtruc0309** [comment]
And can you provide your checkpoint in the paper

**Comment by yanbeic** [comment]
Hi the missing file can be generated after you train the model. 
You would have to run the model to get the checkpoint.
